server:
  port: ${PORT:8082}

spring:
  application:
    name: catalog-service # El nuevo nombre profesional

  datasource:
    # Apunta a localhost por el puerto externo 5434 hacia catalog_db
    url: ${DB_URL:jdbc:postgresql://localhost:5434/catalog_db}
    username: ${DB_USER:user_catalog}
    password: ${DB_PASS:password_catalog}

  rabbitmq:
    host: ${RABBIT_HOST:localhost}
    port: ${RABBIT_PORT:5672}
    username: ${RABBIT_USER:guest}
    password: ${RABBIT_PASS:guest}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true